"""Application-wide constants to avoid magic numbers."""

from __future__ import annotations

# Database
MAX_QUERY_RESULTS = 10000
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# Scraping
DEFAULT_SCRAPE_INTERVAL_SECONDS = 21600  # 6 hours
DEFAULT_RSS_INTERVAL_SECONDS = 300  # 5 minutes
DEFAULT_PPR_INTERVAL_SECONDS = 604800  # 1 week
MAX_SCRAPE_RETRIES = 3
REQUEST_TIMEOUT_SECONDS = 30
SCRAPE_DELAY_MIN_SECONDS = 2.0
SCRAPE_DELAY_MAX_SECONDS = 5.0

# Geocoding
GEOCODER_RATE_LIMIT_SECONDS = 1.0
GEOCODER_MAX_RETRIES = 3

# Price matching
SIMILAR_PROPERTY_PRICE_TOLERANCE = 0.2  # ±20%
SIMILAR_PROPERTY_BEDROOM_RANGE = 1  # ±1 bedroom
SIMILAR_PROPERTY_LIMIT = 6

# Alerts
ALERT_CLEANUP_DAYS = 90
ALERT_EVALUATION_DELAY_MINUTES = 15

# LLM
LLM_DEFAULT_MAX_TOKENS = 2000
LLM_DEFAULT_TEMPERATURE = 0.3
LLM_BATCH_SIZE = 50
LLM_TIMEOUT_SECONDS = 120

# Source management
SOURCE_ERROR_THRESHOLD = 5  # Auto-disable after N consecutive errors

# Nearby search
NEARBY_SOLD_RADIUS_KM = 5.0
NEARBY_SOLD_LIMIT = 10
DEFAULT_SEARCH_RADIUS_KM = 2.0

# Search relevance and comparable-sales matching thresholds
PROPERTY_KEYWORD_TRGM_MIN_SIMILARITY = 0.2
SOLD_COMPS_DEFAULT_MIN_SIMILARITY = 0.86
SOLD_COMPS_HIGH_CONFIDENCE_MIN_SCORE = 0.95

# Search quality benchmark gates (used by scripts/benchmark_search_quality.py)
SEARCH_BENCHMARK_MIN_RESULT_COVERAGE = 0.7
SEARCH_BENCHMARK_MIN_TOP_OVERLAP = 0.45
SEARCH_BENCHMARK_MIN_TOP3_OVERLAP = 0.35

# Admin
MIGRATION_TIMEOUT_SECONDS = 120
MIGRATION_STATUS_TIMEOUT_SECONDS = 30
